export const vnList = [
  {
    romaji: "Hakuchuumu no Aojashin",
    image: "https://t.vndb.org/cv/17/85317.jpg",
    id: 1,
    title: "白昼夢の青写真",
    alias: "The girl who's called the world",
    playTime: "31h21m",
    publisher: [
      "(jp)Laplacian & Syawase Works & The Math God",
      "(cn)Laplacian & Syawase Works & Dir-A",
      "(en)Laplacian & Syawase Works & The Math God",
      "(kr)Team Myskrpatch",
    ],
    relation: [
      "Kimi to Yumemishi",
      "Newton to Ringo no Ki",
      "Mirai Radio to Jinkou-bato",
    ],
    links: [
      "Wikipedia (ja)",
      "Wikidata",
      "GameFAQs,",
      "VGMdb",
      "ACDB",
      "HowLongToBeat",
      "IGDB",
      "IGDB",
      "Lutris",
      "VNStat",
    ],
    description:
      "Kaito wakes to find himself in a strange room with no memories of who he is or how he got there. The only other people around are a quiet white-haired girl and their overseer, Izumo. As three separate stories unfold around him, Kaito begins to wake up to the truth of this world, and his own role in it. And it's all connected to the strange, silent girl named Yonagi...",
  },
  {
    romaji: "Aiyoku no Eustia",
    image: "https://t.vndb.org/cv/78/79678.jpg",
    id: 2,
    title: "穢翼のユースティア",
    alias: "Eustia of the Tarnished Wings",
    playTime: "40h58m",
    publisher: [
      "(jp)AUGUST & Dramatic Create & ENTERGRAM",
      "(en)Yandere Translations & Eustia Translations",
      "(cn)Fengdi Hanhuazu & CK-GAL & Mahou Shounen Esuka ☆ Emuka & Yuegui Liuli Chinese Localization Group",
      "(ru)Nasha Versija & Wonderland & SovietRus & Epic Eagle Team",
      "(hu)laczy90",
      "(kr)Team Myskrpatch",
      "(vn)Hoshi Translation",
      "(ina)IndoCalize Project",
    ],
    links: [
      "Wikipedia (en)",
      "Wikipedia (ja)",
      "Wikidata",
      "IGDB",
      "Lutris",
      "VNStat",
    ],
    description:
      "Five hundred years ago, angered by humanity's sins and arrogance, God recalled his Angels from Earth and the surface was consumed by Chaos. The last person who still prayed to God, the first Saint Irene, asked for his forgiveness. God listened to her prayers and lifted the city and land around her to save humanity from extinction. As the last bastion of humanity, the city of Novus Aether floats in the sky above the inhospitable surface, powered by the daily prayers of the Saint. More than a decade ago, due to the interruption of the prayer, the Gran Forte occurred, causing part of the city to fall to the surface and splitting the lower city in two. In time, the lowest layer became the dwelling of all kinds of low-lives, people who lost much of their former lives during the Gran Forte, becoming known as the Prison. However, a contagious disease that causes people to grow wings has spread throughout the city. A special unit has been formed to deal with these people swiftly. In this Prison resides Caim Astraea, a freelance ex-assassin who does odd jobs for his friends for money, refusing jobs that require him to kill people. During one request, Caim finds a girl who contracts the wing-disease, enveloped in a light that reminds Caim of the Gran Forte years ago...",
  },
];
